version: "3.1"

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: main
    volumes:
      - ./src:/var/www/html
  database:
    image: mysql:8.1
    ports:
      - "43306:3306"
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: wp_password
